#!/bin/sh

# Disable periodic(8) reports, as well as tasks that generate lots of I/O.
sysrc -v -f /etc/periodic.conf          \
  daily_show_success=NO                 \
  daily_show_info=NO                    \
  daily_clean_disks_verbose=NO          \
  daily_clean_tmps_verbose=NO           \
  daily_clean_preserve_verbose=NO       \
  daily_clean_rwho_verbose=NO           \
  daily_backup_passwd_enable=NO         \
  daily_backup_aliases_enable=NO        \
  daily_backup_gpart_enable=NO          \
  daily_status_disks_enable=NO          \
  daily_status_zfs_zpool_list_enable=NO \
  daily_status_network_enable=NO        \
  daily_status_uptime_enable=NO         \
  daily_status_mailq_enable=NO          \
  daily_status_security_enable=NO       \
  daily_status_mail_rejects_enable=NO   \
  daily_status_world_kernel=NO          \
  weekly_show_success=NO                \
  weekly_show_info=NO                   \
  weekly_locate_enable=NO               \
  weekly_whatis_enable=NO               \
  weekly_status_security_enable=NO      \
  monthly_show_success=NO               \
  monthly_show_info=NO                  \
  monthly_accounting_enable=NO          \
  monthly_status_security_enable=NO     \
  security_show_success=NO              \
  security_show_info=NO                 \
  security_status_chksetuid_enable=NO   \
  security_status_neggrpperm_enable=NO  \
  security_status_chkmounts_enable=NO   \
  security_status_chkuid0_enable=NO     \
  security_status_passwdless_enable=NO  \
  security_status_logincheck_enable=NO  \
  security_status_ipfwdenied_enable=NO  \
  security_status_ipfdenied_enable=NO   \
  security_status_pfdenied_enable=NO    \
  security_status_ipfwlimit_enable=NO   \
  security_status_ipf6denied_enable=NO  \
  security_status_kernelmsg_enable=NO   \
  security_status_loginfail_enable=NO   \
  security_status_tcpwrap_enable=NO

# Sendmail-specific stuff
sysrc -v -f /etc/periodic.conf          \
  daily_clean_hoststat_enable=NO        \
  daily_status_mail_rejects_enable=NO   \
  daily_status_include_submit_mailq=NO  \
  daily_submit_queuerun=NO
