#!/bin/sh

set -eu -o pipefail

prog=$(basename "$(readlink -f "$0")")
usage="${prog} [-q] INVIDIOUS_USER INVIDIOUS_DIR"

die() {
  printf '%s: %s\n' "$prog" "$*" 1>&2
  exit 1
}

usage(){
  printf 'usage: %s\n' "$usage" 1>&2
  exit 2
}

while getopts hq opt; do
  case $opt in
    h) usage ;;
    q) exec 1>/dev/null ;;
  esac
done
shift $((OPTIND - 1))

[ $# -eq 2 ] || usage

invidious_user=$1
invidious_dir=$2

cd "$invidious_dir"

su -m "$invidious_user" -c 'git fetch'
local_rev=$(su -m "$invidious_user" -c 'git rev-parse HEAD')
upstream_rev=$(su -m "$invidious_user" -c 'git rev-parse "@{u}"')

if [ "$local_rev" != "$upstream_rev" ]; then
  echo "updating invidious to rev ${remote_rev}"
  su -m "$invidious_user" -c 'git pull --ff-only && shards install --production && crystal build src/invidious.cr --release'
else
  echo "invidious already up to date at rev ${local_rev}"
fi

service invidious restart
