#!/bin/sh

# PROVIDE: nslcd
# REQUIRE: NETWORKING slapd ldconfig resolv kstart
# BEFORE: syslogd
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable the nslcd daemon:
#
# nslcd_kstart_enable="YES"
#

. /etc/rc.subr

name=nslcd
rcvar=nslcd_kstart_enable

load_rc_config ${name}

: ${nslcd_kstart_enable:='NO'}
: ${nslcd_princ:="host/$(hostname -f)"}
: ${nslcd_keytab:='/etc/krb5.keytab'}
: ${nslcd_ccache:="/tmp/krb5cc_$(id -u nslcd)"}

pidfile='/var/run/nslcd.pid'
procname='/usr/local/sbin/nslcd'
command='/usr/local/bin/k5start'
command_args="-abFLq -c ${pidfile} -f ${nslcd_keytab} -g nslcd -o nslcd -k ${nslcd_ccache} ${nslcd_princ} -- /usr/local/sbin/nslcd --nofork"
start_precmd=nslcd_prestart

nslcd_prestart() {
  install -d -o nslcd -g nslcd /var/run/nslcd
}

run_rc_command "$1"
