#!/bin/sh

set_loader_conf      \
  if_iwm_load=YES    \
  iwm8265fw_load=YES

sysrc -v wlans_iwm0='wlan0'

set_sysctl dev.acpi_ibm.0.handlerevents='0x10 0x11'

install_file -m 0555 /usr/local/libexec/thinkpad-brightness
install_file -m 0644 /etc/devd/thinkpad-brightness.conf

service devd restart
