log_level: info
domain: ${invidious_hostname}.${domain}
external_port: 443
channel_threads: 1
feed_threads: 1
database_url: postgres://${invidious_user}@${invidious_dbhost}/${invidious_dbname}?sslmode=verify-full
use_pubsub_feeds: false
hmac_key: ${invidious_hmac_key}
https_only: true
registration_enabled: true
port: ${invidious_port}
host_binding: 127.0.0.1
popular_enabled: false
captcha_enabled: false
check_tables: true
cache_annotations: true

default_user_preferences:
  dark_mode: auto
  autoplay: false
  continue: true
  continue_autoplay: false
  local: true
  quality: dash
  quality_dash: 1080p
  locale: en-US
  region: US
  related_videos: true
  video_loop: false
  player_style: invidious
  default_home: Subscriptions
  feed_menu: [Subscriptions, Playlists]

