#!/bin/sh

# Create host object (if it doesn't exist).
ldap_add "cn=${BOXCONF_HOSTNAME},${hosts_basedn}" <<EOF
objectClass: device
objectClass: domainRelatedObject
objectClass: ldapPublicKey
objectClass: krb5KDCEntry
cn: ${BOXCONF_HOSTNAME}
associatedDomain: ${fqdn}
krb5PrincipalName: host/${fqdn}@${realm}
krb5KeyVersionNumber: 0
krb5KDCFlags: ${krb5_default_princ_flags}
krb5MaxLife: ${krb5_max_ticket_lifetime}
krb5MaxRenew: ${krb5_max_renew_lifetime}
$(cat /etc/ssh/ssh_host_*_key.pub | cut -d' ' -f-2 | sed 's/^/sshPublicKey: /')
description: $(uname -mrs) ${BOXCONF_HOSTCLASS}
EOF

# Create A record.
ldap_add "dc=${BOXCONF_HOSTNAME},dc=${domain},${dns_basedn}" <<EOF
objectClass: dNSDomain
objectClass: domainRelatedObject
dc: ${BOXCONF_HOSTNAME}
aRecord: ${BOXCONF_DEFAULT_IPV4}
associatedDomain: ${fqdn}
EOF

# Create PTR record.
rdns=$(ip2rdns "$BOXCONF_DEFAULT_IPV4")
ldap_add "dc=${rdns%%.*},dc=${rdns#*.},${dns_basedn}" <<EOF
objectClass: dNSDomain2
objectClass: domainRelatedObject
dc: ${rdns%%.*}
pTRRecord: ${fqdn}
associatedDomain: ${rdns}
EOF

# Update attributes that may have changed.
ldap_modify "cn=${BOXCONF_HOSTNAME},${hosts_basedn}" <<EOF
replace: sshPublicKey
$(cat /etc/ssh/ssh_host_*_key.pub | cut -d' ' -f-2 | sed 's/^/sshPublicKey: /')
-
replace: description
description: $(uname -mrs) ${BOXCONF_HOSTCLASS}
EOF

# LDAP service principal for slapd.
ldap_add "cn=ldap/${fqdn},${services_basedn}" <<EOF
objectClass: applicationProcess
objectClass: krb5Principal
objectClass: krb5KDCEntry
cn: ldap/${fqdn}
krb5PrincipalName: ldap/${fqdn}@${realm}
krb5KeyVersionNumber: 0
krb5KDCFlags: ${kdc_default_princ_flags}
krb5MaxLife: ${kdc_max_ticket_lifetime}
krb5MaxRenew: ${kdc_max_renew_lifetime}
EOF
