#!/bin/sh

: ${davical_user:='s-davical'}
: ${davical_uid:='20001'}
: ${davical_dbname:='davical'}
: ${davical_dbhost:="${postgres_host}.${domain}"}
: ${davical_admin_email:="$root_email"}
: ${dav_access_role:='dav-access'}

davical_repo=https://gitlab.com/sacredheartsc/davical.git/
davical_branch=allow-kerberos-fallback

davical_awl_repo=https://gitlab.com/davical-project/awl.git/
davical_awl_branch=master

davical_repo_dir=/usr/local/www/davical
davical_awl_repo_dir=/usr/local/share/awl
davical_webroot="${davical_repo_dir}/htdocs"

davical_tls_cert=/usr/local/etc/nginx/davical.crt
davical_tls_key=/usr/local/etc/nginx/davical.key
davical_keytab="${keytab_dir}/davical.keytab"
davical_client_keytab="${keytab_dir}/davical-client.keytab"
davical_fpm_socket=/var/run/fpm-davical.sock

davical_psql(){
  boxconf_psql                 \
    --host="$davical_dbhost"   \
    --dbname="$davical_dbname" \
    "$@"
}

# Install required packages.
pkg install -y                \
  git                         \
  kstart                      \
  nginx                       \
  php${php_version}           \
  php${php_version}-calendar  \
  php${php_version}-curl      \
  php${php_version}-gettext   \
  php${php_version}-iconv     \
  php${php_version}-ldap      \
  php${php_version}-opcache   \
  php${php_version}-pdo_pgsql \
  php${php_version}-pgsql     \
  php${php_version}-session   \
  php${php_version}-xml

# Install davical from git.
[ -d "$davical_repo_dir" ]     || git clone "$davical_repo"     "$davical_repo_dir"
[ -d "$davical_awl_repo_dir" ] || git clone "$davical_awl_repo" "$davical_awl_repo_dir"

# Update git repos.
git -C "$davical_repo_dir"     pull --ff-only
git -C "$davical_repo_dir"     switch "$davical_branch"
git -C "$davical_awl_repo_dir" pull --ff-only
git -C "$davical_awl_repo_dir" switch "$davical_awl_branch"

# Create davical user account.
create_robot               \
  -c "Davical Pseudo-User" \
  -u "$davical_uid"        \
  -d "$davical_repo_dir"   \
  "$davical_user"

# Get keytab for davical user.
get_keytab                  \
  -o root                   \
  -g "$davical_user"        \
  -m 0640                   \
  "$davical_client_keytab"  \
  "$davical_user"

# Generate davical configuration.
install_template -m 0644                          \
  "${davical_repo_dir}/config/config.php"         \
  "${davical_repo_dir}/config/administration.yml"

# Create postgres user and database.
create_postgres_user "$davical_dbhost" "$davical_user"
create_postgres_db   "$davical_dbhost" "$davical_dbname"

# Initialize davical database.
if ! davical_psql -c 'SELECT 1 FROM awl_db_revision'; then
  davical_psql                                             \
    -f "${davical_awl_repo_dir}/dba/awl-tables.sql"        \
    -f "${davical_awl_repo_dir}/dba/schema-management.sql" \
    -f "${davical_repo_dir}/dba/davical.sql"
  boxconf_kinit "${davical_repo_dir}/dba/update-davical-database" --debug --nopatch
  davical_psql -f "${davical_repo_dir}/dba/base-data.sql"
  boxconf_kinit "${davical_repo_dir}/dba/update-davical-database" --debug
#  davical_psql -c "delete from usr where username = 'admin';"
fi

# Create HTTP service principal and keytab.
create_service "HTTP/${fqdn}"
get_keytab           \
  -m 0640            \
  -o root            \
  -g www             \
  "$davical_keytab"  \
  "HTTP/${fqdn}"

# Copy TLS certificate for nginx.
install_certificate     -m 0644 "$fqdn" "$davical_tls_cert"
install_certificate_key -m 0600 "$fqdn" "$davical_tls_key"

# Generate nginx configuration.
install_file -m 0644 /usr/local/etc/nginx/fastcgi_params
install_template -m 0644           \
  /usr/local/etc/nginx/nginx.conf  \
  /usr/local/etc/nginx/vhosts.conf

# Generate php-fpm configuration.
install_file -m 0644               \
  /usr/local/etc/php.ini           \
  /usr/local/etc/php-fpm.conf
install_template -m 0644                \
  /usr/local/etc/php-fpm.d/davical.conf
rm -f /usr/local/etc/php-fpm.d/www.conf

# Enable and start daemons.
sysrc -v                                         \
  nginx_enable=YES                               \
  php_fpm_enable=YES                             \
  kstart_instances+=davical                      \
  kstart_davical_keytab="$davical_client_keytab" \
  kstart_davical_flags="-aLK 120 -g ${davical_uid} -o ${davical_uid} -k /tmp/krb5cc_${davical_uid} -u ${davical_user}"
service kstart restart
service nginx restart
service php-fpm restart

# Sync groups from LDAP.
su -m "$davical_user" -c "${davical_repo_dir}/scripts/cron-sync-ldap.php ${fqdn}"

# Create cron job for keeping LDAP groups up-to-date.
install_template -m 0644 /etc/cron.d/davical-update-groups

# Create dav access role.
create_role "$dav_access_role"
