#!/bin/sh

: ${desktop_access_role:='desktop-access'}
: ${desktop_access_gid:='40000'}

wifi_tls_cert=/usr/local/etc/ssl/wifi.crt
wifi_tls_key=/usr/local/etc/ssl/wifi.key

load_kernel_module linux linux64

pkg install -y             \
  chromium                 \
  drm-kmod                 \
  eclipse                  \
  firefox                  \
  gajim                    \
  gnucash                  \
  juk                      \
  k3b                      \
  kde5                     \
  kid3-qt6                 \
  kmix                     \
  konversation             \
  libreoffice              \
  libva-intel-media-driver \
  makemkv                  \
  sddm                     \
  stow                     \
  tmux                     \
  tree                     \

set_sysctl                         \
  net.local.stream.recvspace=65536 \
  net.local.stream.sendspace=65536 \
  kern.sched.preempt_thresh=224    \
  vfs.usermount=1                  \
  hw.snd.latency=7

set_loader_conf                             \
  kern.ipc.shmseg=1024                      \
  kern.ipc.shmmni=1024                      \
  kern.maxproc=100000                       \
  linux_load=YES                            \
  linux64_load=YES                          \
  acpi_ibm_load=YES                         \
  compat.linuxkpi.i915_enable_dc=2          \
  compat.linuxkpi.i915_enable_fbc=1         \
  compat.linuxkpi.i915_fastboot=1           \
  compat.linuxkpi.i915_disable_power_well=1 \
  machdep.hwpstate_pkg_ctrl=0               \
  vfs.zfs.txg.timeout=10                    \
  hw.pci.do_power_nodriver=3

# Set USB power savings
usbconfig | awk -F: '{ print $1 }' | xargs -rtn1 -I%  usbconfig -d % power_save ||:
install_file /etc/rc.local

# Install host certificate.
install_certificate     -m 0644 "dc=${BOXCONF_HOSTNAME},${hosts_basedn}" "$wifi_tls_cert"
install_certificate_key -m 0600 "dc=${BOXCONF_HOSTNAME},${hosts_basedn}" "$wifi_tls_key"

# Configure wpa_supplicant.
install_template -m 0644 /etc/wpa_supplicant.conf

# Create desktop access role.
create_role -g "$desktop_access_gid" "$desktop_access_role"

# Create polkit rules for shutdown/reboot/suspend
install_template -m 0644 /usr/local/etc/polkit-1/rules.d/51-desktop-access.rules

# Create desktop devfs ruleset.
install_template -m 0644 /etc/devfs.rules

# Create devd rule for lid lock.
install_file -m 0555 /usr/local/libexec/kde-lock-and-suspend
install_file -m 0644 /etc/devd/lidlock.conf

# Create desktop-access sudo role.
ldap_add "cn=desktop-access,${sudo_basedn}" <<EOF
objectClass: sudoRole
cn: desktop-access
sudoUser: %${desktop_access_role}
sudoCommand: /usr/local/bin/networkmgr
sudoRunAsUser: ALL
sudoRunAsGroup: ALL
sudoOption: !authenticate
EOF

# Add current host to desktop-access sudo role.
ldap_ensure_attribute "cn=desktop-access,${sudo_basedn}" sudoHost "$fqdn"

# Enable kwallet pam module.
install_file -m 0644 /etc/pam.d/sddm

# Copy SDDM config file.
install_template /usr/local/etc/sddm.conf

# Create policy file for firefox.
install_directory -m 0755 /usr/local/lib/firefox/distribution
install_template -m 0644  /usr/local/lib/firefox/distribution/policies.json

# Create policy file for chromium.
install_directory -m 0755                  \
  /usr/local/etc/chromium/policies         \
  /usr/local/etc/chromium/policies/managed
install_template -m 0644 /usr/local/etc/chromium/policies/managed/policies.json

# Create xdg override directory.
install_directory -m 0755          \
  /usr/local/override              \
  /usr/local/override/applications

# Create xdg application overrides.
install_file -m 0644 \
  /usr/local/override/applications/signal-desktop.desktop

# Configure libreoffice
install_file -m 0644 /usr/local/lib/libreoffice/program/sofficerc

# Create profile script for KDE environment variables.
install_file -m 0644 /etc/profile.d/kde.sh

sysrc -v                                       \
  dbus_enable=YES                              \
  sddm_enable=YES                              \
  kld_list+='i915kms'                          \
  devfs_system_ruleset=desktop                 \
  create_args_wlan0='country US regdomain FCC' \
  ifconfig_wlan0="WPA inet ${ipv4_address} netmask ${ipv4_netmask} powersave"

load_kernel_module i915kms

service devfs restart
service devd restart
service dbus status || service dbus start
service sddm status || service sddm start
