#!/bin/sh

: ${postgres_max_connections:='50'}
: ${postgres_shared_buffers:="$(( memsize  / 2 ))"}
: ${postgres_work_mem:="$(( memsize / 4 / ${postgres_max_connections} ))"}
: ${postgres_maintenance_work_mem:="$(( memsize / 20 ))"}
: ${postgres_temp_buffers:="$((32 * 1024 * 1024))"}
: ${postgres_effective_cache_size:="$(( memsize * 3 / 4 ))"}

postgres_version=15
postgres_user=postgres
postgres_home=/var/db/postgres
postgres_data_dir="${postgres_home}/data${postgres_version}"
postgres_tls_cert="${postgres_home}/postgres.crt"
postgres_tls_key="${postgres_home}/postgres.key"
postgres_keytab="${keytab_dir}/postgres.keytab"

pkg install -y postgresql15-server

# Create ZFS dataset for postgresql data.
create_dataset                     \
  -o "mountpoint=${postgres_home}" \
  -o recordsize=16k                \
  -o primarycache=metadata         \
  -o atime=off                     \
  "${state_dataset}/postgres"
install_directory -m 0755 -o "$postgres_user" -g "$postgres_user" "$postgres_home"

# Initialize the database.
sysrc -v postgresql_enable=YES
[ -d "${postgres_data_dir}" ] || service postgresql initdb

# Create service principal and keytab.
create_krb5_service "postgres/${fqdn}"
get_keytab            \
  -o root             \
  -g "$postgres_user" \
  -m 0640             \
  "$postgres_keytab"  \
  "postgres/${fqdn}"

# Create postgresql PAM service.
install_file -m 0644 /etc/pam.d/postgresql

# Copy TLS certificate for postgres.
install_certificate     -m 0644 -o root -g "$postgres_user" "$fqdn" "$postgres_tls_cert"
install_certificate_key -m 0640 -o root -g "$postgres_user" "$fqdn" "$postgres_tls_key"

# Generate postgresql configuration.
install_template -m 0600 -o "$postgres_user" -g "$postgres_user" \
  "${postgres_data_dir}/postgresql.conf"                         \
  "${postgres_data_dir}/pg_hba.conf"
install_file -m 0600 -o "$postgres_user" -g "$postgres_user" \
  "${postgres_data_dir}/pg_ident.conf"

service postgresql status || service postgresql start
service postgresql reload
