#!/bin/sh

set -eu -o pipefail

ports_tree=latest

# update ports tree
poudriere ports -u -p "$ports_tree" > /dev/null

for jail in "$@"; do
  poudriere jail -u -j "$jail" > /dev/null
  poudriere bulk -j "$jail" -f  /usr/local/etc/poudriere.d/pkglist -p "$ports_tree" > /dev/null
done
