#!/bin/sh

set_sysctl(){
  while [ $# -gt 0 ]; do
    sysctl "$1"
    sed -i.bak "/^${1%%=*}=/{
h
s/=.*/=${1#*=}/
}
\${
x
/^\$/{
s//${1}/
H
}
x
}" /etc/sysctl.conf
    shift
  done
  rm -f /etc/sysctl.conf.bak
}

set_loader_conf(){
  [ "$BOXCONF_OS_FAMILY" = freebsd ] || bug 'set_loader_conf can only be used on FreeBSD'

  while [ $# -gt 0 ]; do
    grep -qxF "${1%%=*}=\"${1#*=}\"" /boot/loader.conf || BOXCONF_NEED_REBOOT=true
    sed -i.bak "/^${1%%=*}=/{
h
s/=.*/=\"${1#*=}\"/
}
\${
x
/^\$/{
s//${1%%=*}=\"${1#*=}\"/
H
}
x
}" /boot/loader.conf
    shift
  done
  rm -f /boot/loader.conf.bak
}

load_kernel_module(){
  case $BOXCONF_OS_FAMILY in
    freebsd)
      while [ $# -gt 0 ]; do
        kldstat -qm "$1" || kldload -v "$1"
        shift
      done
      ;;
    *)
      die "load_kernel_module unimplemented for ${BOXCONF_OS_FAMILY}"
      ;;
  esac
}
