#!/bin/sh

_boxconf_ip2dec(){
  while [ $# -gt 0 ]; do
    echo "$1" | {
      IFS=./ read -r _bcipd_a _bcipd_b _bcipd_c _bcipd_d _bcipd_e
      [ -n "$_bcipd_e" ] || _bcipd_e=32
      printf '%s %s ' "$((_bcipd_a<<24|_bcipd_b<<16|_bcipd_c<<8|_bcipd_d))" "$((-1<<(32-_bcipd_e)))"
    }
    shift
  done
}

ip_in_subnet(){
  _boxconf_ip2dec "$1" "$2" | {
    read -r _bciis_a1 _bciis_m1 _bciis_a2 _bciis_m2 ||:
    test "$(( (_bciis_a1 & _bciis_m2) == (_bciis_a2 & _bciis_m2) && _bciis_m1 >= _bciis_m2 ))" -eq 1
  }
}

prefix2netmask(){
  _bcp2n_val=$(( 0xffffffff ^ ((1 << (32 - $1)) - 1) ))
  echo "$(( (_bcp2n_val >> 24) & 0xff )).$(( (_bcp2n_val >> 16) & 0xff )).$(( (_bcp2n_val >> 8) & 0xff )).$(( _bcp2n_val & 0xff ))"
}

ip2rdns(){
  echo "$1" | awk -F. '{print $4"."$3"."$2"."$1".in-addr.arpa"}'
}
