#!/bin/sh

: ${solr_version:='9.4.0'}
: ${solr_uid:='161'}
: ${tika_version:='2.9.1'}
: ${tika_uid:='787'}
: ${dovecot_vmail_uid:='793'}
: ${dovecot_recipient_delimiter:='+'}
: ${dovecot_default_quota:='10G'}
: ${dovecot_quota_grace_percent:='5'}

: ${rspamd_host:='smtp'}
: ${lmtp_port:='25'}
: ${quota_status_port:='10993'}
: ${mail_access_role:='mail-access'}

solr_user=solr
solr_data_dir=/var/db/solr
solr_conf_dir=/usr/local/etc/solr
solr_heap_size=2g
solr_softcommit_ms=60000
solr_url="https://dlcdn.apache.org/solr/solr/${solr_version}/solr-${solr_version}-slim.tgz"
solr_port=8983
solr_install_dir=/usr/local/solr

tika_user=tika
tika_data_dir=/var/db/tika
tika_conf_dir=/usr/local/etc/tika
tika_heap_size=2g
tika_port=9998
tika_url="https://dlcdn.apache.org/tika/${tika_version}/tika-server-standard-${tika_version}.jar"
tika_install_dir=/usr/local/tika

dovecot_user=dovecot
dovecot_login_user=dovenull
dovecot_vmail_user=vmail
dovecot_vmail_uid=793
dovecot_vmail_dir=/var/db/vmail
dovecot_conf_dir=/usr/local/etc/dovecot
dovecot_script_dir=/usr/local/libexec/dovecot
dovecot_sieve_before_dir="${dovecot_conf_dir}/sieve-before.d"
dovecot_sieve_pipe_bin_dir="${dovecot_script_dir}/sieve-pipe"
dovecot_keytab="${keytab_dir}/dovecot.keytab"
dovecot_dhparams="${dovecot_conf_dir}/dhparams.pem"
dovecot_tls_cert="${dovecot_conf_dir}/dovecot.crt"
dovecot_tls_key="${dovecot_conf_dir}/dovecot.key"
dovecot_cipherlist='ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305'
dovecot_quota_mail_from="postmaster@${email_domain}"
