#!/bin/sh

# Apache Solr is used by dovecot for full-text search.

pkg install -y curl openjdk17

# Create local solr group.
pw groupshow "$solr_user" \
  || pw groupadd "$solr_user" -g "$solr_uid"

# Create local solr user.
pw usershow "$solr_user" \
  || pw useradd "$solr_user" \
       -u "$solr_uid"        \
       -g "$solr_user"       \
       -c 'Apache Solr'      \
       -d "$solr_data_dir"   \
       -s /usr/sbin/nologin

# Create ZFS dataset for solr DB.
create_dataset -o "mountpoint=${solr_data_dir}" "${state_dataset}/solr"

# Set ownership on solr DB dir.
install_directory -m 0770 -o "$solr_user" -g "$solr_user" "$solr_data_dir"

# Create solr install/config directories.
install_directory -m 0755 \
  "$solr_install_dir"     \
  "$solr_conf_dir"

# Download and extract the solr tarball.
curl -fL "$solr_url" | tar xf - -C "$solr_install_dir" --strip-components 1

# Copy solr rc script.
install_file -m 0555 /usr/local/etc/rc.d/solr

# Copy solr config files.
install_file -m 0644                \
  "${solr_conf_dir}/solrconfig.xml" \
  "${solr_conf_dir}/log4j2.xml"

# Copy the default solr config from the distribution.
install -v -m 0644 -o "$solr_user" -g "$solr_user" \
  "${solr_install_dir}/server/solr/solr.xml"       \
  "${solr_data_dir}/solr.xml"

# Enable and start solr.
sysrc -v                           \
  solr_enable=YES                  \
  solr_heap_size="$solr_heap_size"

# Start solr.
service solr restart

# Create solr collection for dovecot.
[ -d "${solr_data_dir}/dovecot" ] \
  || JAVA_TOOL_OPTIONS='-Xmx64m' su -m "$solr_user" -c "${solr_install_dir}/bin/solr create -c dovecot -p ${solr_port}"

# Copy solr configs for dovecot.
install_file -m 0644 -o "$solr_user" -g "$solr_user" \
  "${solr_data_dir}/dovecot/conf/schema.xml"         \
  "${solr_data_dir}/dovecot/conf/solrconfig.xml"
rm -f "${solr_data_dir}/dovecot/conf/managed-schema.xml"

# Restart solr.
service solr restart
