#!/bin/sh

organization='SacredHeartSC Test Environment'
domain=test.sacredheartsc.com
email_domain=sacredheartsc.com
ssid=sacredheartsc-test
locale=en_US.UTF-8
timezone=America/New_York
root_authorized_keys='ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICy6mAAeVe2eo5j/d+vLOATvLCOTvp2BMjI9aeW7KcwI'

# Hard-code some IPs here so that hosts can be accessed without DNS.
pkg_host_ipv4='10.11.199.4'
smtp_host_ipv4='10.11.199.5'

idm_servers='idm1 idm2'
slapd_server_ids="\
1 10.11.199.2
2 10.11.199.3"

# Generate with `rspamadm keypair`. Set corresponding private key in ./90-vault:
rspamd_pubkey='uedcfqt9j4q3rassh3ajog7qti64s643rdti9ea38supj9eayddy'

vlan_ids='130 199'

vlan130_cidr='10.11.130.0/24'
vlan130_gateway='10.11.130.1'
vlan130_ntp_servers='10.11.130.1'

vlan199_cidr='10.11.199.0/24'
vlan199_gateway='10.11.199.1'
vlan199_ntp_servers='10.11.199.1'

radius_clients=unifi
radius_unifi_address=10.11.130.0/24
