#!/bin/sh

fqdn=${BOXCONF_HOSTNAME}.${domain}

allowed_tcp_ports=ssh
allowed_udp_ports=

boxconf_user='s-boxconf'
boxconf_password='changeme'

root_password='changeme'

realm=$(echo "$domain" | tr '[:lower:]' '[:upper:]')
basedn=$(echo "$domain" | sed -e 's/^/dc=/' -e 's/\./,dc=/g')
resolvers=$(echo "$slapd_server_ids" | awk '{print $2}')

ldap_uri=$(printf "ldap://%s.${domain}/ " $idm_servers)
accounts_basedn="ou=accounts,${basedn}"
people_basedn="ou=people,${accounts_basedn}"
robots_basedn="ou=robots,${accounts_basedn}"
hosts_basedn="ou=hosts,${accounts_basedn}"
services_basedn="ou=services,${accounts_basedn}"
groups_basedn="ou=groups,${basedn}"
private_groups_basedn="ou=userprivate,${groups_basedn}"
roles_basedn="ou=roles,${groups_basedn}"
automount_basedn="ou=automount,${basedn}"
sudo_basedn="ou=sudo,${basedn}"
dns_basedn="ou=dns,${basedn}"

nslcd_min_uid=1000
nscd_ttl=600
nscd_negative_ttl=20

krb5_max_ticket_lifetime=86400 # 1 day
krb5_max_renew_lifetime=604800 # 1 week
krb5_default_princ_flags=382      # requires-pre-auth

system_ccache_group=sysccache
system_ccache_gid=788
ssh_authorized_keys_user=authzkeys
ssh_authorized_keys_uid=789

tcp_buffer_size=2097152  # suitable for 1 GigE

nproc=$(nproc)

nginx_worker_processes=$nproc
nginx_nofile=2048
nginx_worker_connections=768
nginx_ssl_ciphers='ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305'

# The poudriere server must be built before the IDM servers, which results
# in a chicken-and-egg problem with DNS. When the $no_idm extra var is set,
# just use Google DNS.
#
# The idea is that we'll run boxconf on the pkg server again *after* the IDM
# servers are built, which will set everything correctly.
if [ -n "${no_idm:-}" ]; then
  resolvers='8.8.8.8  8.8.4.4'
fi
