#!/bin/sh

###############################################################################
## Kerberos / LDAP related functions.
##
## These functions allow the $boxconf_user to obtain Kerberos credential caches
## and perform LDAP queries.
##
## - $boxconf_user, $boxconf_password, and $realm must be set.
## - Only Heimdal KRB5 is supported.
## - Appropriate krb5.conf and ldap.conf must exist on the host.
###############################################################################

boxconf_ccache='/tmp/krb5cc_boxconf'
boxconf_test_ccache='/tmp/krb5cc_boxconf_test'

BOXCONF_CLEANUP_PATHS="${BOXCONF_CLEANUP_PATHS} ${boxconf_ccache} ${boxconf_test_ccache}"

boxconf_kinit(){
  klist -c "$boxconf_ccache" -t \
    || printf '%s' "$boxconf_password" \
      | kinit -c "$boxconf_ccache" --password-file=STDIN "${boxconf_user}@${realm}"
}

get_keytab(){
  # $1 = keytab, $2..$n = princ

  _gkt_owner=0
  _gkt_group=0
  _gkt_mode=600

  while getopts m:o:g: _gkt_opt; do
    case $_gkt_opt in
      m) _gkt_mode=$OPTARG ;;
      o) _gkt_owner=$OPTARG ;;
      g) _gkt_group=$OPTARG ;;
    esac
  done
  shift $((OPTIND - 1))

  _gkt_keytab=$1; shift

  # Set permissions on the keytab file.
  if [ -f "$_gkt_keytab" ]; then
    chmod "$_gkt_mode" "$_gkt_keytab"
    chown "$_gkt_owner" "$_gkt_keytab"
    chgrp "$_gkt_group" "$_gkt_keytab"
  else
    install -Cv -m "$_gkt_mode" -o "$_gkt_owner" -g "$_gkt_group" /dev/null "$_gkt_keytab"
  fi

  # Acquire kadmin service ticket.
  printf '%s' "$boxconf_password" \
    | kinit -c "$boxconf_ccache" -S "kadmin/admin@${realm}" --password-file=STDIN "${boxconf_user}@${realm}"

  # For each principal...
  while [ $# -gt 0 ]; do
    if kinit -c "$boxconf_test_ccache" -t "$_gkt_keytab" "$1" true; then
      # If the keytab is valid for the principal, continue.
      shift; continue
    else
      # Otherwise, reset the keys and store them in the keytab.
      KRB5CCNAME="$boxconf_ccache" ktutil -v -k "$_gkt_keytab" get -p "${boxconf_user}@${realm}" "${1}@${realm}"
    fi
    shift
  done
}

boxconf_kadmin(){
  printf '%s' "$boxconf_password" \
    | boxconf_kinit -c "$boxconf_ccache" -S "kadmin/admin@${realm}" --password-file=STDIN "${boxconf_user}@${realm}" \
      && KRB5CCNAME="$boxconf_ccache" kadmin -r "$realm" -p "${boxconf_user}@${realm}" "$@"
}

ldap_search(){
  boxconf_kinit && KRB5CCNAME="$boxconf_ccache" ldapsearch -QLLL "$@"
}

ldap_add(){
  _ldapa_dn=$1; shift
  boxconf_kinit \
    && KRB5CCNAME="$boxconf_ccache" ldapsearch -QLLL -s base -b "$_ldapa_dn" dn > /dev/null 2>&1 \
    || { printf 'dn: %s\n' "$_ldapa_dn"; cat; } | KRB5CCNAME="$boxconf_ccache" ldapadd -Q "$@"
}

ldap_modify(){
  _ldapm_dn=$1; shift
  boxconf_kinit \
    && { printf 'dn: %s\nchangetype: modify\n' "$_ldapm_dn"; cat; } \
      | KRB5CCNAME="$boxconf_ccache" ldapmodify -Q "$@"
}

ldap_delete(){
  boxconf_kinit && KRB5CCNAME="$boxconf_ccache" ldapdelete -Q "$@"
}

create_krb5_service(){
  while [ $# -gt 0 ]; do
    ldap_add "cn=${1},${services_basedn}" <<EOF
objectClass: applicationProcess
objectClass: krb5Principal
objectClass: krb5KDCEntry
cn: ${1}
krb5PrincipalName: ${1}@${realm}
krb5KeyVersionNumber: 0
krb5KDCFlags: ${krb5_default_princ_flags}
krb5MaxLife: ${krb5_max_ticket_lifetime}
krb5MaxRenew: ${krb5_max_renew_lifetime}
EOF
    shift
  done
}
